/**
 * Gives a plain Markdown link its link styling.
 *
 * `styles/shell.css` styles a prose link through `.article a.inline` — an
 * underline and the accent colour. Nothing was ever adding that class, so every
 * bare `[text](url)` fell through to the `a { color: inherit; text-decoration:
 * inherit }` in reset.css and rendered as body text: still a link, still
 * clickable, with nothing on screen to say so. This plugin is the missing half
 * of that rule.
 *
 * It runs on the Markdown AST, which is why it is a rehype plugin and not a
 * widened `.article a` selector. An anchor emitted by a component — Button's
 * `<a class="button ...">`, a Card, a heading's permalink — is an MDX JSX node,
 * never an element in this tree, so the plugin cannot reach it and those
 * components keep their own appearance by construction. A CSS selector broad
 * enough to catch prose links would have had to exclude each of them by hand.
 *
 * Two anchors are left alone:
 *
 *   an anchor that already carries a class — an author who wrote raw HTML in
 *   MDX chose that appearance, and this plugin does not argue.
 *
 *   a GFM footnote reference or back-reference. Those are markers, not prose:
 *   underlining a superscript `1` reads as a typo.
 */
import type { Element, Root } from 'hast';

/** Any node with children, including the MDX JSX nodes a component becomes. */
interface Parent {
  children?: unknown[];
}

/** A marker generated by GFM's footnote handling rather than written as prose. */
const isFootnoteMarker = (properties: Element['properties']) =>
  'dataFootnoteRef' in properties || 'dataFootnoteBackref' in properties;

export function rehypeInlineLinks() {
  return (tree: Root) => {
    const visit = (node: Parent) => {
      if (!Array.isArray(node.children)) return;
      for (const child of node.children as Element[]) {
        if (child.type === 'element' && child.tagName === 'a') {
          const properties = (child.properties ??= {});
          if (!properties.className && !isFootnoteMarker(properties)) {
            properties.className = ['inline'];
          }
        }
        visit(child as Parent);
      }
    };
    visit(tree);
  };
}
